name: Update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * */2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name "Leonardo Rivero"
        git config user.email "codingleonardo@gmail.com"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Actualizar README.md con informacion actualizada"
        git push origin master
